In [1]:
import cv2
import numpy as np
import tensorflow as tf

In [2]:
path = 'haarcascade_frontalface_default.xml'
font_scale = 1.5
font = cv2.FONT_HERSHEY_PLAIN
rectangle_bgr = (255, 255, 255)
img = np.zeros((500, 500))
text = "Some Text in box"
Classes = ['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']


In [3]:
(text_width, text_height) = cv2.getTextSize(text, font, fontScale=font_scale, thickness=1)[0]

In [4]:
text_offset_x = 10
text_offset_y = img.shape[0]-25
box_coords = ((text_offset_x, text_offset_y), (text_offset_x+ text_width+2, text_offset_y-text_height-2))
cv2.rectangle(img, box_coords[0], box_coords[1], rectangle_bgr, cv2.FILLED)
cv2.putText(img, text, (text_offset_x, text_offset_y), font, fontScale=font_scale, color=(0, 0, 0), thickness=1)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
new_model = tf.keras.models.load_model('my_model_64p35.h5')

In [ ]:
cap = cv2.VideoCapture(1)
if cap.isOpened():
  cap = cv2.VideoCapture(0)
if not cap.isOpened():
  raise IOError("cannot open webcam")

while True:
  ret, frame = cap.read()
  cv2.imshow('Frame', frame)
  print(frame)
  faceCascade= cv2.CascadeClassifier(cv2.data.haarcascades+ 'haarcascade_frontalface_default.xml')
  gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
  faces = faceCascade.detectMultiScale(gray, 1.1, 4)
  for x, y, w, h in faces:
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = frame[y:y+h, x:x+w]
    cv2.rectangle(frame, (x,y), (x+w, y+h), (255, 0, 0), 2)
    facess = faceCascade.detectMultiScale(roi_gray)
    if len(facess) ==0:
      print("Face not detected")
    else:
      for ex,ey,ew,eh in facess:
        face_roi = roi_color[ey:ey+eh, ex: ex+ew]
    final_image= cv2.resize(face_roi, (224, 224))
    final_image = np.expand_dims(final_image, axis=0)
    final_image = final_image/255.0

    font = cv2.FONT_HERSHEY_SIMPLEX
    Predictions = new_model.predict(final_image)
    font_scale = 1.5
    font = cv2.FONT_HERSHEY_PLAIN
    status = Classes[np.argmax(Predictions)]
    x1,y1,w1,h1 = 0 , 0, 175, 75
    cv2.rectangle(frame, (x1, x1), (x1+w1, y1+h1), (0, 0, 0), -1)
    cv2.putText(frame, status, (x1 +int(w1/10), y1+int(h1/2)), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
    cv2.putText(frame, status, (100, 150), font, 3, (0, 0, 255), 2, cv2.LINE_4)
    cv2.rectangle(frame, (x,y), (x+w, y+h), (0, 0, 255))
  key = cv2.waitKey(1)
  if key == ord('q'):
    break

cap.release()
cv2.destroyAllWindows()

[[[48 55 23]
  [51 56 29]
  [52 55 32]
  ...
  [ 0  0  5]
  [ 0  0  5]
  [ 0  0  5]]

 [[51 56 26]
  [48 53 26]
  [48 53 30]
  ...
  [ 0  0  2]
  [ 0  0  2]
  [ 0  0  2]]

 [[49 56 26]
  [45 52 25]
  [46 52 29]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[ 0  3  0]
  [ 0  3  0]
  [ 0  3  0]
  ...
  [ 2  5  0]
  [ 0  3  0]
  [ 0  3  0]]

 [[ 0  3  0]
  [ 0  3  0]
  [ 0  3  0]
  ...
  [ 2  5  0]
  [ 2  4  0]
  [ 0  2  0]]

 [[ 0  3  0]
  [ 0  3  0]
  [ 0  3  0]
  ...
  [ 3  6  0]
  [ 3  6  0]
  [ 0  3  0]]]
[[[255 255 214]
  [255 255 220]
  [255 255 226]
  ...
  [ 72  46  78]
  [ 81  46  79]
  [ 79  44  77]]

 [[255 255 215]
  [255 255 221]
  [255 255 226]
  ...
  [ 74  47  81]
  [ 76  45  82]
  [ 75  43  80]]

 [[255 255 221]
  [255 255 225]
  [255 255 230]
  ...
  [ 74  43  76]
  [ 78  43  76]
  [ 73  38  71]]

 ...

 [[ 74 108  61]
  [ 75 110  65]
  [ 80 115  73]
  ...
  [ 93 115  63]
  [ 94 115  63]
  [ 93 114  62]]

 [[ 69 103  63]
  [ 66 103  65]
  [ 71 109  74]
  ...
  

NameError: name 'face_roi' is not defined

Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\ashis\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\ashis\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "c:\Users\ashis\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\ashis\anaconda3\lib\asyncio\selector_events.py", line 115, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed b

: 

In [33]:
cv2.VideoCapture(0)

< cv2.VideoCapture 00000193E7BB0D70>